version: '3'
services:
  node-starter:
    image: "joepuzzo/node-starter"
    ports:
     - "4040:8080"
    environment:
     - NODE_ENV=dev
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
